### ISSUE TITLE
Invalid token

### ISSUE THREAD

**Issue by GreyMatter658** [Brooklyn888/BYPASSBOT#1]
I

**Comment by Brooklyn888** [comment]
> I deployed your bot on heroku after forking your repo & changed your bot token to mine and than deployed but logs says token is invalid & i used the correct one i checked it

**Comment by Brooklyn888** [comment]
Message To @bruce_3_33 in Telegram. He is the owner of this repository.

**Comment by Brooklyn888** [comment]
Message To @bruce_3_33 in Telegram. He is the owner of this repository.He Will Tell You the process.
